name: Node configs

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn run publish
